package Master;

import connection.DBConnect;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.SQLException;

public class PaketPembelajaran extends JFrame{
    private JTable tblPaketPembelajaran;
    private JButton tambahButton;
    private JButton lihatButton;
    private JButton ubahButton;
    private JButton hapusButton;
    private JTextField tbidpkt;
    private JComboBox cbmapel1;
    private JComboBox cbmapel2;
    private JTextField tbnamapkt;
    private JComboBox cbjenjang;
    private JComboBox cbkelas;
    private JTextField tbharga;
    private JTextField tbmasaberlaku;
    private JTextField tbstatuspkt;
    private JPanel kelolapaketpembelajaran;

    DefaultTableModel model;

    DBConnect connect = new DBConnect();

    String idpkt, namapkt, idmpl1, idmpl2, jenjang,kelas;

    double harga;

    int masaberlaku, status;

    public PaketPembelajaran(){
        setContentPane(kelolapaketpembelajaran);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setSize(400, 500);
        model = new DefaultTableModel();
        tblPaketPembelajaran.setModel(model);
        addColumn();
        loadData();
        tbidpkt.setText(getAutoGeneratedID());
        tbstatuspkt.setText("Aktif");
        tbstatuspkt.setEditable(false);
        clear();

        cbjenjang.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (cbjenjang.getSelectedItem().equals("SMP")){
                    cbkelas.removeAllItems();
                    cbkelas.addItem("7");
                    cbkelas.addItem("8");
                    cbkelas.addItem("9");
                }else if (cbjenjang.getSelectedItem().equals("SMA")){
                    cbkelas.removeAllItems();
                    cbkelas.addItem("10");
                    cbkelas.addItem("11");
                    cbkelas.addItem("12");
                }else {
                    cbkelas.removeAllItems();
                }
            }
        });
        cbkelas.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                cbmapel1.removeAllItems();
                tampilMapel();
            }
        });
        cbmapel1.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                cbmapel2.removeAllItems();
                tampilMapel2();
            }
        });
    }

    public String getAutoGeneratedID() {
        String id = "";
        try {
            connect.stat = connect.conn.createStatement();
            String query = "SELECT MAX(SUBSTRING(id_pkt, 4, LEN(id_pkt))) AS ID FROM tblPaketPembelajaran";
            connect.result = connect.stat.executeQuery(query);

            if (connect.result.next()) {
                String lastID = connect.result.getString("ID");
                if(lastID != null){
                    int incrementedID = Integer.parseInt(lastID) + 1;
                    id = "PK" + String.format("%03d", incrementedID);
                }else {
                    id= "PK001";
                }
            }
            connect.stat.close();
            connect.result.close();
        } catch (SQLException e) {
            System.out.println("Terjadi kesalahan: " + e.getMessage());
        }
        return id;
    }

    public void addColumn() {
        model.addColumn("Id Paket");
        model.addColumn("Id Mapel 1");
        model.addColumn("Id Mapel 2");
        model.addColumn("Nama Paket");
        model.addColumn("Jenjang");
        model.addColumn("Kelas");
        model.addColumn("Harga");
        model.addColumn("Masa Berlaku");
        model.addColumn("Status Paket");
    }
    public void loadData() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            DBConnect connection = new DBConnect();
            connection.stat = connection.conn.createStatement();
            String querry = "SELECT * FROM tblPaketPembelajaran";
            connection.result = connection.stat.executeQuery(querry);
            while (connection.result.next()) {
                Object[] obj = new Object[9];
                obj[0] = connection.result.getString("id_pkt");
                obj[1] = connection.result.getString("id_mpl_1");
                obj[2] = connection.result.getString("id_mpl_2");
                obj[3] = connection.result.getString("nama_pkt");
                obj[4] = connection.result.getString("jenjang");
                obj[5] = connection.result.getString("kelas");
                obj[6] = connection.result.getDouble("harga");
                obj[7] = connection.result.getInt("masa_berlaku");
                obj[8] = connection.result.getInt("status_pkt");
                model.addRow(obj);
            }
            connection.stat.close();
            connection.result.close();
        } catch (Exception e) {
            System.out.println("Terjadi error saat load data item: " + e);
        }
    }

    public void tampilMapel(){
        try {
            DBConnect connection = new DBConnect();
            connection.stat = connection.conn.createStatement();
            String sql = "SELECT id_mpl, nama_mpl, jenjang, kelas, status_mpl FROM tblMapel where status_mpl=1 AND kelas='"+cbkelas.getSelectedItem()+"'";
            connection.result = connection.stat.executeQuery(sql);

            while (connection.result.next()){
                cbmapel1.addItem(connection.result.getString("nama_mpl"));
            }
            connection.stat.close();
            connection.result.close();
        }catch (SQLException ex){
            System.out.println("Terjadi error saat load data mata pelajaran"+ex);
        }
    }

    public void tampilMapel2(){
        try {
            DBConnect connection = new DBConnect();
            connection.stat = connection.conn.createStatement();
            String sql = "SELECT id_mpl, nama_mpl, jenjang, kelas, status_mpl FROM tblMapel where status_mpl=1 AND kelas = '"+cbkelas.getSelectedItem()+"' AND nama_mpl != '"+cbmapel1.getSelectedItem()+"'";
            connection.result = connection.stat.executeQuery(sql);

            while (connection.result.next()){
                cbmapel2.addItem(connection.result.getString("nama_mpl"));
            }
            connection.stat.close();
            connection.result.close();
        }catch (SQLException ex){
            System.out.println("Terjadi error saat load data mata pelajaran"+ex);
        }
    }

    private void clear() {
        tbidpkt.setText(getAutoGeneratedID());
        cbmapel1.setSelectedIndex(-1);
        cbmapel2.setSelectedIndex(-1);
        tbnamapkt.setText("");
        cbjenjang.setSelectedIndex(-1);
        cbkelas.setSelectedIndex(-1);
        tbharga.setText("");
        tbmasaberlaku.setText("");
        tbstatuspkt.setText("Aktif");
    }

    public static void main(String[] args) {
        JFrame tcGUI =  new PaketPembelajaran();
        tcGUI.setVisible(true);
    }

}
